### ISSUE TITLE
Plugging in USB port to laptop causes lockup/power cycle

### ISSUE THREAD

**Issue by mccauleyma** [Northeastern-Electric-Racing/shepherd_bms#103]
Currently have only tested while charging, but it seems to be the case that any time I have disconnected from the BMS and then plug the port back in the BMS will fault. 

The fault is trigger upon plugging into laptop, NOT initializing serial monitor. By the time I reconnect via serial the BMS says it is no longer faulted, indicating a power cycle/lockup.

Issue likely began when we added watchdog? Perhaps this is just lag during serial init causing watchdog to die?

**Comment by dyldonahue** [comment]
@mccauleyma this is still a thing right?
