### ISSUE TITLE
Make Matt's Weekend fix pretty

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#107]
**What are you proposing?**
We did a lot of brute force main loop type thing

**What files/components does this concern?**
Mostly main, probably just going through and adding comments and documents

**What would this improve over how it is now?**
This would make the code more readable

**Estimated time commitment**
Maybe a couple hours

**Comment by dyldonahue** [comment]
closing since it was kinda addressed / remaining stuff will be scoped into smaller stuff
