### ISSUE TITLE
Broadcast Pack temp with BMS Status Message

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#128]
**Please describe the problem, specifically and concisely**
We need to format and send out a CAN message that contains some pack temperature information. The format of the message can be found [here in NER Processing](https://github.com/Northeastern-Electric-Racing/Nero/blob/0e68332f710f5881bc9ebb99a32d39f786fe777d/ner_processing/decode_data.py#L27). It's a message called "BMS Status" and contains average and pack temp. Here is a [spreadsheet of BMS messages](https://docs.google.com/spreadsheets/d/1Jwh-KIG3L45pp-cewxkHfCTKLNiE6Sq8YxyrIO65hV4/edit#gid=0) for reference.

Probably put stuff in compute.h and compute.cpp alongside the other CAN messages, and broadcast them every cycle

Also, fix "SendShudtdownControlMessage" function. Right now, that uses a union to redundantly package one byte. This is unnecessary and the lone byte can just be assigned. This part will make a lot more sense when looking at it

**Comment by dyldonahue** [comment]
^ can follow the same exact structure as used for the other CAN broadcasts in these files such as "SendCurrentStatus", "SendCellVoltageMessage", "SendShutdownControlMessage"
