### ISSUE TITLE
Make sending the charger CAN message use a union rather than the funky bitshfiting

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#132]
**What are you proposing?**

**What files/components does this concern?**

**What would this improve over how it is now?**

**Estimated time commitment**

**Comment by dyldonahue** [comment]
(compute.cpp line 58)

@mccauleyma wth is going on with this. There's already a union set up presumably with the correct size for each element, what came up that caused the need for all the bit shifting in the CAN msg itself.

**Comment by dyldonahue** [comment]
@nwdepatie matt said that this was put in place because when testing the union seemed to break for a while. 

Given that, I think we should cautiously try removing all the funky bit shifting at a time where we can test it right away to see if our union works as expected or not. On hold until then
