### ISSUE TITLE
Change fault detection from counters to timers

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#137]
Right now the way we detect faults is if the BMS detects a fault however many times, then we will fault. This is to eliminate noise.

There is also a delay in main for 10 milliseconds, and if we remove it the faults will occur because we are detecting noise faster and more often and not letting the noise settle. These counters should be moved to timers so that we can adjust the amount of time that a fault has to occur in order to cause a fault. This will probably be a better practice.

**Comment by dyldonahue** [comment]
(these fault checks start at line 240 in main.cpp). We have a Timer class that is implemented in various places throughout the code, but feel free to ask any questions if you are having trouble implementing it

refer to this convo for some explanation of what should be done:
![efefef](https://user-images.githubusercontent.com/98500199/217378431-83ce15e7-7571-47c5-9a97-d3dcb19f394b.jpg)
