### ISSUE TITLE
Change SOC calculation from LUT to coulomb counting

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#164]
We should transition from a LUT to coulomb counting for state of charge estimation

https://www.batterydesign.net/soc-estimation-by-coulomb-counting/

**Comment by dyldonahue** [comment]
NOTE: this is sort of done, but on hold until we figure out how to calibrate

**Comment by dyldonahue** [comment]
CLOSING AS TODO FOR V2 ON STM

no longer feel like this makes sense to get done on V1 before porting to STM, so closing and will reopen later in the summer. NOTE : do not delete the working branch for this ticket, will probably end up using most of the functionality
