### ISSUE TITLE
We need to monitor internal temp and fault if too high

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#166]
literally the description. This relates to the onboard SHT30 that we are using to monitor the temperature of the board itself. If the board overheats we want to fault.

**Comment by dyldonahue** [comment]
@nwdepatie i assume there is a real chance this chip/interface may look different on new boards & with stm right? Wondering if it makes sense to put  this on hold and re open in the fall, we are porbably going to have a lot more faults to add anyway and this could fit with that. Dont wanna spend time on this if the chip an d interface are changing

**Comment by dyldonahue** [comment]
Closing for now, noting to reopen and implement with new sht driver in the fall
