### ISSUE TITLE
Adding Nonvolatile fault logging

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#167]
I'm thinking that we utilize an SD card or EEPROM to keep a running log of faults that is retained even after a power cycle/exiting faulting

**Comment by dyldonahue** [comment]
CLOSING THIS AS A TODO FOR V2 ON STM 

no longer feel this makes sense as a ticket to finish before porting over, so am going to re-open in the new repo later this summer
