### ISSUE TITLE
Implement Charging Logic

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#23]
This will utilize the "Charger" API from the compute board to say when the car should/should not be charging and if we are allowing charging

**Comment by dyldonahue** [comment]
BALANCING:
- In charge mode (pin is high)
- highest cell is above 4.1
- Cell delta is above threshold (probably like 0.01V)


CHARGING:
- In charge mode
- Max cell is below max cell voltage (4.2V probs)
- Charger is not timed out (should make this a setting too)

- When we start charging, reset timeout timer (charger off time)
- Stop charging and start timeout timer when high cell = max voltage
