### ISSUE TITLE
Implement Motor Controller class to track current motor controller state/info

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#24]
We should probably have an internal representation of the motor controller inside the BMS, so we need to implement that and route CAN data to it respectively

**Comment by dyldonahue** [comment]
note: make final decision on re scoping compute class before doing this. On hold for now

**Comment by dyldonahue** [comment]
when we die we go bye bye - this ticket, circa 2023
