### ISSUE TITLE
Implement Voltage and Current Calculations

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#29]
For this ticket, we need to calculate:
2) End of Discharge Voltage (EDV)
3) Compensated End of Discharge Voltage (CEDV)
4) Current Rate (C-Rate) [Potentially via coulomb counting ?]

**Comment by dyldonahue** [comment]
closing as completely unnecessary, but still noting in case this changes in the future. After looking into some of these, we dont even have the data needed to calculate some of them and it would be well out of current scope to find a way to get that data.
