### ISSUE TITLE
Refactor LTC library

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#42]
There is a lot of stuff that is a bit funky about all of the code that we can tidy up/improve

For instance, wrcomm writes a message to every single chip instead of just one, meaning that every single thermistor is selected and then serialized

**Comment by nwdepatie** [comment]
Also a lot of build warnings

**Comment by dyldonahue** [comment]
This would just involve re-organizing / formatting / optimizing (no new features or anything). Good challenge for someone who wants to dive more into code readability / optimization
