### ISSUE TITLE
Fix Thermistor multiplexing on high side

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#62]
There is a possibility that we may be reading in the wrong order of therms on the high side due to the direction of the multiplexer, so we might need to redo the ```selectTherm()``` function

**Comment by nwdepatie** [comment]
Might need to reevaluate this ticket at a different time, not sure if this is the case anymore

**Comment by dyldonahue** [comment]
seemingly no longer the case but i have noted to double check @nwdepatie
