### ISSUE TITLE
Implement better CCL and DCL calculations

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/shepherd_bms#75]
**What are you proposing?**
We need to factor in voltage and any other factors into the DCL and CCL calculations

**What files/components does this concern?**
probably ```calcs.h``` and ```calcs.cpp```

**What would this improve over how it is now?**
Make the CCL and DCL more accurate

**Estimated time commitment**
Maybe like a couple hours, we need to research how and then implement

**Comment by mccauleyma** [comment]
DCL is done! No longer high priority, but CCL should maybe also be done? Should at least assess it and see if Orion does it.

**Comment by dyldonahue** [comment]
@mccauleyma are u content with everything in this ticket or should i keep it open to revisit

**Comment by mccauleyma** [comment]
CCL should be done probably
